version: '3'
services:
  repository:
    image: eclipsevorto/vorto-repo:0.10.0.M6
    ports:
      - "8080:8080"
    volumes:
      - "./repository-web/docker:/code/config"
    networks:
      - backend
  generators:
    depends_on: ["repository"]
    image: eclipsevorto/vorto-generators:0.10.0.M6
    volumes:
      - "./repository-web/docker:/gen/config"
    networks:
      - backend
    command: ["/bin/bash","/gen/wait-for-it.sh","-t","50","localhost:8080","--","/bin/bash","/gen/run_generators.sh"] 

  example-generators:
    depends_on: ["repository"]
    image: eclipsevorto/vorto-generators-3rd-party
    volumes:
      - "./repository-web/docker:/gen/config"
    networks:
      - backend
    command: ["/bin/bash", "/gen/wait-for-it.sh", "-t", "70", "localhost:8080", "--","/bin/bash","/gen/run_generators.sh"] 
   


networks:
  backend:
    driver: bridge
